version: "3.8"

services:
  database:
    image: postgis/postgis:13-master
    env_file:
      - .env_pg
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  inno-work-backend:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env_directus
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
      - ./uploads:/directus/uploads
      - ./snapshot.yaml:/directus/snapshot.yaml
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
#      WEBSOCKETS_ENABLED: "true"
#      HOST: ${VIRTUAL_HOST:-inno-work-backend}
#      VIRTUAL_HOST: ${VIRTUAL_HOST:-backend.inno-work.local}
#      VIRTUAL_PORT: ${VIRTUAL_PORT:-8080}
#      PORT: 8080
      #disable Marketplace in production with set limit to 0 https://github.com/directus/directus/issues/22582
      EXTENSIONS_LIMIT: 0

      SECRET: "cf32986e-6eb8-4a8d-b2b5-ebd0a7b28748"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "cbrunzendorf@next-inno.de"
      ADMIN_PASSWORD: "test"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

networks:
  default:
    external: true
    name: nginx-proxy
